env:
    CONFIG: config.sh
    CIRRUS_SHELL: bash

task:
  name: "TWRP Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 20G

  Sync_script:
      - curl -sL https://raw.githubusercontent.com/rushiranpise/twrp_compiler/main/scripts/sync.sh | bash

  Build_script:
      - curl -sL https://raw.githubusercontent.com/rushiranpise/twrp_compiler/main/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/rushiranpise/twrp_compiler/main/scripts/upload.sh | bash    